import type { ComponentBinding } from "../../../shared/collaborate.js";
import { useState, type ReactNode } from "react";
import type { BoardNode, BoardSnapshot, NodeContent, Assignment } from "../../../shared/board.js";
import { AttemptHistory } from "./AttemptHistory.js";
const sections: {key:keyof NodeContent;label:string}[]=[{key:"prompt",label:"Prompt"},{key:"plan",label:"Plan"},{key:"design",label:"Design"},{key:"implementationNotes",label:"Implementation"}];
export function TaskInspector({board,node,drafts,onDraft,onSave,onDiscard,error,implementation,onReconcile}:{board:BoardSnapshot;node:BoardNode;drafts:Record<string,string>;onDraft:(section:string,value:string)=>void;onSave:(title:string,content:NodeContent,assignment:Assignment|null,collaborate?:ComponentBinding)=>void;onDiscard:()=>void;error?:string;implementation?:ReactNode;onReconcile:()=>void}) {
  const [section,setSection]=useState<keyof NodeContent|"history">("prompt");
  const prefix=`${board.id}/${node.id}/`;
  const value=(field:string,fallback:string)=>drafts[prefix+field]??fallback;
  const content=Object.fromEntries(sections.map(item=>[item.key,value(item.key,node.content[item.key])])) as unknown as NodeContent;
  const assignment=JSON.parse(value("assignment",JSON.stringify(node.assignment))) as Assignment|null;
  const collaborate=JSON.parse(value("collaborate",JSON.stringify(node.collaborate??null))) as ComponentBinding|null;
  const dirty=Object.keys(drafts).some(key=>key.startsWith(prefix));
  return <section className="task-inspector">
    <label>Title<input value={value("title",node.title)} onChange={event=>onDraft("title",event.target.value)}/></label>
    <div className="section-tabs">{sections.map(item=><button key={item.key} aria-pressed={section===item.key} onClick={()=>setSection(item.key)}>{item.label}</button>)}<button aria-pressed={section==="history"} onClick={()=>setSection("history")}>History</button></div>
    {section==="history"?<AttemptHistory boardId={board.id} attempts={board.attempts.filter(attempt=>attempt.nodeId===node.id)}/>:<label>{sections.find(item=>item.key===section)!.label}<textarea aria-label={sections.find(item=>item.key===section)!.label} value={content[section]} placeholder={section==="implementationNotes"?"Implementation notes. Generated code appears after execution.":"No content yet. Write a draft or ask the coordinator."} onChange={event=>onDraft(section,event.target.value)}/></label>}
    {section==="implementationNotes" && implementation}
    {node.kind==="task" && !node.imported && <><label>Execution mode<select value={collaborate?"collaborate":"direct"} onChange={event=>onDraft("collaborate",JSON.stringify(event.target.value==="collaborate"?{masterIdentity:board.members[0]?.identity??"",manifestPath:""}:null))}><option value="direct">Direct task</option><option value="collaborate">Collaborate component</option></select></label>{collaborate && <><label>Component master<select value={collaborate.masterIdentity} onChange={event=>onDraft("collaborate",JSON.stringify({...collaborate,masterIdentity:event.target.value}))}>{board.members.map(member=><option key={member.identity} value={member.identity}>{member.tabName} · {member.sessionId}</option>)}</select></label><label>Collaborate manifest<input value={collaborate.manifestPath} placeholder="Absolute manifest path in work-vault" onChange={event=>onDraft("collaborate",JSON.stringify({...collaborate,manifestPath:event.target.value}))}/></label><p>The master keeps its own Run and coordinates implementations and reviews.</p></>}</>}
    {node.kind==="task" && !node.imported && !collaborate && <label>Assigned agent<select value={assignment?.kind==="member"?assignment.identity:assignment?.kind??""} onChange={event=>onDraft("assignment",JSON.stringify(event.target.value==="new-worker"?{kind:"new-worker",agent:"codex",workspacePath:""}:event.target.value?{kind:"member",identity:event.target.value}:null))}>
      <option value="">Choose an agent</option>{board.members.map(member=><option key={member.identity} value={member.identity}>{member.tabName} · {member.source} · {member.sessionId}</option>)}<option value="new-worker">New worker</option>
    </select></label>}
    {!collaborate && assignment?.kind==="new-worker" && <div className="worker-placement"><label>Agent<select value={assignment.agent} onChange={event=>onDraft("assignment",JSON.stringify({...assignment,agent:event.target.value}))}>{["codex","claude","cursor"].map(agent=><option key={agent}>{agent}</option>)}</select></label><label>Workspace<input value={assignment.workspacePath} onChange={event=>onDraft("assignment",JSON.stringify({...assignment,workspacePath:event.target.value}))} placeholder="Absolute task workspace path"/></label><label>Model (optional)<input value={assignment.model??""} onChange={event=>onDraft("assignment",JSON.stringify({...assignment,model:event.target.value||undefined,effort:event.target.value?assignment.effort:undefined}))}/></label><label>Effort (optional)<input value={assignment.effort??""} disabled={!assignment.model} onChange={event=>onDraft("assignment",JSON.stringify({...assignment,effort:event.target.value||undefined}))}/></label></div>}
    {dirty && <p className="unsaved">Unsaved changes</p>}{error && <><p role="alert">{error}</p><details><summary>Compare current saved revision</summary><pre className="preserve-lines">{JSON.stringify(node.content,null,2)}</pre><button onClick={onReconcile}>Keep my draft on this revision</button></details></>}
    <div className="board-actions"><button disabled={!dirty} onClick={()=>onSave(value("title",node.title),content,collaborate?null:assignment,collaborate??undefined)}>Save</button><button disabled={!dirty} onClick={onDiscard}>Discard</button></div>
  </section>;
}
